# 业务相关配置
[app]
    # 限制ip访问
    whitelist = "127.0.0.1,::1"
    # 并发拉取数据时channel的大小
    chan_size = 100


# server 相关配置
[server]
    # server 运行地址，支持 HTTP 端口 ":port" 或 UNIX Socket "unix:/file"
    addr = ":5000"
    # gin mode ，可选值： debug 、 test 、 release
    mode = "debug"
    # 开启 pprof
    pprof = true
    # 开启 prometheus metrics
    metrics = true