# viper web server 配置文件

########## 部署环境标志
# 该值关联影响其他配置，如数据库， redis 等涉及不同环境的配置
# 如 配置为 localhost ， 使用 goutils 获取 mysql 相关实例时将使用 [mysql.localhost] 的配置
env = "localhost"


########## 业务相关配置
[app]
    # 限制ip访问
    whitelist = "127.0.0.1,::1"


########## server 相关配置
[server]
    # server 运行地址，支持 HTTP 端口 ":port" 或 UNIX Socket "unix:/file"
    addr = ":5000"
    # gin mode ，可选值： debug 、 test 、 release
    mode = "debug"
    # 开启 pprof
    pprof = true
    # 开启 prometheus metrics
    metrics = true